export class OCPPException extends Error {
  constructor(message, code) {
    super(message);
    this.name = "OCPPException";
    this.code = code;
    this.message = message;
  }

  toJSON() {
    return {
      name: this.name,
      code: this.code,
      message: this.message,
    };
  }
}

export const OCPPExceptionCode = {
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_RESPONSE: "INVALID_RESPONSE",
  INVALID_SIGNAL: "INVALID_SIGNAL",
  INVALID_DATA: "INVALID_DATA",
  INVALID_FORMAT: "INVALID_FORMAT",
  INVALID_PARAMETERS: "INVALID_PARAMETERS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_AUTHORIZATION: "INVALID_AUTHORIZATION",
  INVALID_TRANSACTION: "INVALID_TRANSACTION",
  INVALID_RESERVATION: "INVALID_RESERVATION",
  INVALID_METER_VALUES: "INVALID_METER_VALUES",
  INVALID_STATUS_NOTIFICATION: "INVALID_STATUS_NOTIFICATION",
  INVALID_DATA_TRANSFER: "INVALID_DATA_TRANSFER",
  INVALID_FIRMWARE_STATUS_NOTIFICATION: "INVALID_FIRMWARE_STATUS_NOTIFICATION",
  INVALID_DIAGNOSTICS_STATUS_NOTIFICATION:
    "INVALID_DIAGNOSTICS_STATUS_NOTIFICATION",
  INVALID_HEARTBEAT: "INVALID_HEARTBEAT",
  INVALID_BOOT_NOTIFICATION: "INVALID_BOOT_NOTIFICATION",
  INVALID_AUTHORIZE: "INVALID_AUTHORIZE",
  INVALID_START_TRANSACTION: "INVALID_START_TRANSACTION",
  INVALID_STOP_TRANSACTION: "INVALID_STOP_TRANSACTION",
  INVALID_METER_VALUES: "INVALID_METER_VALUES",
  INVALID_STATUS_NOTIFICATION: "INVALID_STATUS_NOTIFICATION",
  INVALID_DATA_TRANSFER: "INVALID_DATA_TRANSFER",
  INVALID_FIRMWARE_STATUS_NOTIFICATION: "INVALID_FIRMWARE_STATUS_NOTIFICATION",
  INVALID_DIAGNOSTICS_STATUS_NOTIFICATION:
    "INVALID_DIAGNOSTICS_STATUS_NOTIFICATION",
  INVALID_HEARTBEAT: "INVALID_HEARTBEAT",
  INVALID_BOOT_NOTIFICATION: "INVALID_BOOT_NOTIFICATION",
  INVALID_AUTHORIZE: "INVALID_AUTHORIZE",
  INVALID_START_TRANSACTION: "INVALID_START_TRANSACTION",
};
